language: R
sudo: required
#cache: packages
dist: trusty

warnings_are_errors: false

notifications:
  email:
    - daniel.antal@ceemid.eu

r_packages:
  - backports
  - devtools
  - dplyr
  - ggplot2
  - jsonlite
  - knitr  
  - roxygen2
  - rvest  
  - testthat
  - tidyr
  - magrittr
  - dplyr
  - purrr
  - rmarkdown
  - knitr
  - usethis

  
r_github_packages:
  - jimhester/covr


env:
  global:
  - WARNINGS_ARE_ERRORS=1
  - GITHUB_REPO: antaldaniel/regions

r_build_args: "--no-resave-data --no-build-vignettes"
r_check_args: "--as-cran --no-build-vignettes"    

apt_packages:
  - libudunits2-dev
  - udunits2
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - libcairo2-dev
  - protobuf-compiler
  - valgrind
  - libgdal20
  - libspatialite-dev 
  - libproj-dev
  - libgeos-dev
  - libgdal1-dev
  - libgdal-dev
  - libgeos-c1v5
  - libjq-dev
  - netcdf-bin


before_install:
  - pip install --user codecov
  - sudo apt-get -qq update

r:
- release
- oldrel

after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'