language: R
sudo: required
#cache: packages
dist: trusty

warnings_are_errors: false

notifications:
  email:
    - daniel.antal@ceemid.eu

r_packages:
  - backports
  - devtools
  - dplyr
  - ggplot2
  - jsonlite
  - knitr  
  - roxygen2
  - rvest  
  - testthat
  - tidyr
  - magrittr
  - dplyr
  - purrr
  - rmarkdown
  - knitr
  - usethis

  
r_github_packages:
  - jimhester/covr


env:
  global:
  - WARNINGS_ARE_ERRORS=1
  - GITHUB_REPO: antaldaniel/regions

r_build_args: "--no-resave-data --no-build-vignettes"
r_check_args: "--as-cran --no-build-vignettes"    

apt_packages:
  - libudunits2-dev
  - udunits2
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - libcairo2-dev
  - protobuf-compiler
  - valgrind
  - libgdal20
  - libspatialite-dev 
  - libproj-dev
  - libgeos-dev
  - libgdal1-dev
  - libgdal-dev
  - libgeos-c1v5
  - libjq-dev
  - netcdf-bin


before_install:
  - pip install --user codecov
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler
  - sudo apt-get install libssl-dev
  - sudo apt-get install libcairo2-dev  
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get --yes install npm
  

  # activate liblwgeom by:
  - sudo ldconfig
  - Rscript -e 'install.packages("dplyr")'  
  - Rscript -e 'install.packages("magrittr")'
  - Rscript -e 'install.packages("stats")'
  - Rscript -e 'install.packages("purrr")'  
  - Rscript -e 'install.packages("tidyr")'
  - Rscript -e 'install.packages("rmarkdown")'     
  - Rscript -e 'install.packages("usethis")'
  - Rscript -e 'install.packages("roxygen2")'     
  - Rscript -e 'install.packages("testthat")'     
  - Rscript -e 'install.packages("knitr")'

r:
- release
- oldrel

after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'